# Generated by Django 3.1.5 on 2021-02-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('expence_date', models.DateField()),
                ('bill_amount', models.IntegerField()),
                ('images', models.ImageField(upload_to='expence/images')),
            ],
        ),
    ]
