# Generated by Django 3.1.5 on 2021-02-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210221_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='people',
        ),
    ]
