# Generated by Django 3.1.5 on 2021-02-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210221_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='people',
        ),
    ]
