# Generated by Django 3.1.5 on 2021-02-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210221_2113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admins',
        ),
    ]
