# Generated by Django 3.1.5 on 2021-04-02 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210221_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='expence',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
