# Generated by Django 3.1.5 on 2021-04-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_expence_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
