# Generated by Django 3.1.5 on 2021-04-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210403_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='paid_upto',
            field=models.CharField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
