# Generated by Django 3.1.5 on 2021-04-03 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_member_paid_upto'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
