# Generated by Django 3.1.5 on 2021-04-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_member_date_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Members',
        ),
    ]
