# Generated by Django 3.1.5 on 2021-04-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210406_1117'),
    ]

    operations = [

        migrations.AddField(
            model_name='members',
            name='status',
            field=models.CharField(default='active', max_length=40),
            preserve_default=False,
        ),
    ]
