# Generated by Django 3.1.5 on 2021-04-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210407_1136'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='members',
            name='del_reason',
            field=models.CharField(default='not yet', max_length=80),
            preserve_default=False,
        ),
    ]
