# Generated by Django 3.1.5 on 2021-04-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210408_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='join_date',
            field=models.DateField(),
        ),
    ]
