# Generated by Django 3.1.5 on 2021-04-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210410_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(max_length=20)),
                ('for_month', models.CharField(max_length=50)),
                ('flat_no', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='admins',
        ),
    ]
