# Generated by Django 3.1.5 on 2021-04-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='del_reason',
            field=models.CharField(default='not yet', max_length=20),
            preserve_default=False,
        ),
    ]
