# Generated by Django 3.1.5 on 2021-04-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210410_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_purpose', models.CharField(max_length=100)),
                ('payee_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(max_length=20)),
                ('flat_no', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('del_reason', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FistivalFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fistival_name', models.CharField(max_length=50)),
                ('payee_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(max_length=20)),
                ('flat_no', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('del_reason', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPurposeFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_purpose', models.CharField(max_length=100)),
                ('payee_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(max_length=20)),
                ('flat_no', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('del_reason', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='del_reason',
            field=models.CharField(max_length=50),
        ),
    ]
