# Generated by Django 3.1.5 on 2021-04-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210410_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FistivalFunds',
            new_name='FestivalFunds',
        ),
    ]
