# Generated by Django 3.1.5 on 2021-04-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210410_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyfunds',
            old_name='emergency_purpose',
            new_name='Emergency_purpose',
        ),
    ]
