# Generated by Django 3.1.5 on 2021-04-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210411_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='del_reason',
            field=models.CharField(max_length=80),
        ),
    ]
