# Generated by Django 3.1.5 on 2021-04-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210412_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festivalfunds',
            old_name='fistival_name',
            new_name='festival_name',
        ),
    ]
