# Generated by Django 3.1.5 on 2021-04-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210413_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='images',
            field=models.FileField(upload_to='main/expence/images'),
        ),
    ]
